spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: customer
    password: pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default-schema: public
        jdbc:
          lob:
            non_contextual_creation: true
